### ISSUE TITLE
I use 0.10.1,but come across this mistake : Shape of labels 1 does not match shape of predictions 2

### ISSUE THREAD

**Issue by xiazi-yu** [Yuting-Gao/CRNN_Mxnet#1]
[18:42:02] src/operator/././cudnn_algoreg-inl.h:65: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
Traceback (most recent call last):
  File "text_deep_ocr_bucketing.py", line 121, in <module>
    batch_end_callback  = mx.callback.Speedometer(BATCH_SIZE, 20))
  File "/usr/lib/python2.7/site-packages/mxnet-0.10.1-py2.7.egg/mxnet/module/base_module.py", line 495, in fit
    self.update_metric(eval_metric, data_batch.label)
  File "/usr/lib/python2.7/site-packages/mxnet-0.10.1-py2.7.egg/mxnet/module/bucketing_module.py", line 462, in update_metric
    self._curr_module.update_metric(eval_metric, labels)
  File "/usr/lib/python2.7/site-packages/mxnet-0.10.1-py2.7.egg/mxnet/module/module.py", line 680, in update_metric
    self._exec_group.update_metric(eval_metric, labels)
  File "/usr/lib/python2.7/site-packages/mxnet-0.10.1-py2.7.egg/mxnet/module/executor_group.py", line 561, in update_metric
    eval_metric.update_dict(labels_, preds)
  File "/usr/lib/python2.7/site-packages/mxnet-0.10.1-py2.7.egg/mxnet/metric.py", line 91, in update_dict
    self.update(label, pred)
  File "/usr/lib/python2.7/site-packages/mxnet-0.10.1-py2.7.egg/mxnet/metric.py", line 1005, in update
    check_label_shapes(labels, preds)
  File "/usr/lib/python2.7/site-packages/mxnet-0.10.1-py2.7.egg/mxnet/metric.py", line 24, in check_label_shapes
    "predictions {}".format(label_shape, pred_shape))
ValueError: Shape of labels 1 does not match shape of predictions 2

**Comment by Yuting-Gao** [comment]
I didn't met this problem ever, maybe something wrong with your label.

**Comment by bluseking** [comment]
@Yuting-Gao I also meet the same problem, I just want to recognize the label which include the spaces、letters and numbers，is there any suggestion on the value of the variable num_label?

**Comment by bluseking** [comment]
@Yuting-Gao  [18:38:00] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:107: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
Traceback (most recent call last):
  File "text_deep_ocr_bucketing.py", line 122, in <module>
    batch_end_callback  = mx.callback.Speedometer(BATCH_SIZE, 20))
  File "/home/cad/cad_python2/lib/python2.7/site-packages/mxnet/module/base_module.py", line 520, in fit
    self.update_metric(eval_metric, data_batch.label)
  File "/home/cad/cad_python2/lib/python2.7/site-packages/mxnet/module/bucketing_module.py", line 530, in update_metric
    self._curr_module.update_metric(eval_metric, labels)
  File "/home/cad/cad_python2/lib/python2.7/site-packages/mxnet/module/module.py", line 757, in update_metric
    self._exec_group.update_metric(eval_metric, labels)
  File "/home/cad/cad_python2/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 616, in update_metric
    eval_metric.update_dict(labels_, preds)
  File "/home/cad/cad_python2/lib/python2.7/site-packages/mxnet/metric.py", line 132, in update_dict
    self.update(label, pred)
  File "/home/cad/cad_python2/lib/python2.7/site-packages/mxnet/metric.py", line 1246, in update
    labels, preds = check_label_shapes(labels, preds, True)
  File "/home/cad/cad_python2/lib/python2.7/site-packages/mxnet/metric.py", line 58, in check_label_shapes
    "predictions {}".format(label_shape, pred_shape))
ValueError: Shape of labels 1 does not match shape of predictions 2

this is the error i just met

**Comment by bluseking** [comment]
I find your code can  recognize letters， as for images  filled with letters and numbers  then it will report the above exceptions

**Comment by dlml** [comment]
Hi,i have got a same error

**Comment by bluseking** [comment]
I haven't found a solution to this problem

**Comment by XinyuDu** [comment]
same problem

**Comment by Brightstar217** [comment]
Hello, guys.
Did you solve the problem?
....
ValueError: Shape of labels 1 does not match shape of predictions 2
...

**Comment by Yuting-Gao** [comment]
set "eval_metric         = mx.metric.np(Accuracy)"  in text_deep_ocr_bucketing.py model.fit as 
"eval_metric         = mx.metric.np(Accuracy, allow_extra_outputs=True))"

This works for me.
